cmake_minimum_required(VERSION 3.22.1)
project(gsender_bridge)
if(NOT DEFINED NODE_ROOT)
  set(NODE_ROOT "${CMAKE_CURRENT_LIST_DIR}/../../../../vendor/node")
endif()
add_library(node SHARED IMPORTED)
set_target_properties(node PROPERTIES IMPORTED_LOCATION "${NODE_ROOT}/bin/${ANDROID_ABI}/libnode.so")
add_library(gsender_bridge SHARED bridge.cpp)
target_include_directories(gsender_bridge PRIVATE "${NODE_ROOT}/include/node")
target_compile_options(gsender_bridge PRIVATE -fexceptions -frtti)
target_link_libraries(gsender_bridge node log)
