'use strict';
const {test}=require('node:test'), assert=require('node:assert/strict');
const {fork,execFileSync}=require('node:child_process'), path=require('node:path'), fs=require('node:fs'), os=require('node:os');
const {io}=require('socket.io-client');
const sleep=ms=>new Promise(resolve=>setTimeout(resolve,ms));
async function until(fn,description){for(let i=0;i<80;i++){const value=await fn();if(value)return value;await sleep(100);}throw Error('Timeout: '+description);}
test('packaged Android backend: real gSender controller + two simulated USB endpoints', {timeout:30000}, async()=>{
    const dir=fs.mkdtempSync(path.join(os.tmpdir(),'gsender-pendant-apk-')), payload=path.join(dir,'runtime');
    execFileSync('python3',['-m','zipfile','-e',process.env.PENDANT_TEST_PAYLOAD||path.resolve(__dirname,'../app/src/main/assets/payload.zip'),payload]);
    if(process.env.PENDANT_TEST_SERVER)fs.copyFileSync(process.env.PENDANT_TEST_SERVER,path.join(payload,'server.cjs'));
    if(process.env.PENDANT_TEST_SERVER)for(const name of ['adaptive-mode.js','panel.html','launcher.js','panel.js'])fs.copyFileSync(path.resolve(__dirname,'../pendant',name),path.join(payload,'usb-pendant',name));
    fs.copyFileSync(path.join(__dirname,'pendant-native.cjs'),path.join(dir,'native.cjs'));
    const child=fork(path.join(payload,'bootstrap.cjs'),[],{execArgv:['--no-global-search-paths','--require',path.join(dir,'native.cjs')],env:{...process.env,NODE_PATH:''},stdio:['ignore','pipe','pipe','ipc']});
    const messages=[];let logs='',socket;
    child.on('message',m=>messages.push(m));child.stdout.on('data',b=>logs+=b);child.stderr.on('data',b=>logs+=b);
    try{
        const ready=await until(()=>messages.find(m=>m.host==='ready'),'backend startup '+logs);
        const base='http://127.0.0.1:'+ready.port, key={'x-gsender-key':ready.token};
        assert.equal((await fetch(base+'/api/usb-pendant')).status,403);
        assert.equal((await fetch(base+'/api/usb-pendant/arm',{method:'POST',headers:key})).status,403);
        assert.match(await (await fetch(base+'/pendant/',{headers:key})).text(),/usb-pendant\/launcher.js/);
        assert.equal((await fetch(base+'/usb-pendant/panel.html',{headers:key})).status,200);
        assert.match(await(await fetch(base+'/usb-pendant/panel.html',{headers:key})).text(),/adaptive-mode\.js/);
        assert.equal((await fetch(base+'/usb-pendant/adaptive-mode.js',{headers:key})).status,200);
        const post=async(action,body={})=>{
            const response=await fetch(base+'/api/usb-pendant/'+action,{method:'POST',headers:{...key,'X-USB-Pendant':'1','Content-Type':'application/json'},body:JSON.stringify(body)});
            const value=await response.json(); if(!response.ok)throw Error(JSON.stringify(value));return value;
        };
        const state=async()=> (await fetch(base+'/api/usb-pendant',{headers:key})).json();
        socket=io(base,{transports:['websocket'],extraHeaders:key,reconnection:false});
        await new Promise((resolve,reject)=>{socket.once('connect',resolve);socket.once('connect_error',reject);});
        await new Promise((resolve,reject)=>socket.timeout(3000).emit('open','android-usb:42:0',{baudrate:115200,defaultFirmware:'GrblHAL'},(timeout,err)=>timeout||err?reject(timeout||err):resolve()));
        await post('connect');
        await until(async()=>{const s=await state();return s.ready&&s.cnc.valid;},'ready knob and real controller telemetry');
        assert.equal((await state()).armed,false);
        const body={session:'a'.repeat(32),visible:true,preset:{xyStep:.5,zStep:.1,feedrate:1000,rapidFeedrate:5000}};
        await post('arm',body);
        await sleep(150);child.send({test:'detent',seq:1});child.send({test:'detent',seq:1});
        await until(()=>messages.filter(m=>m.test==='cnc-write'&&m.data.includes('$J=')).length===1,'single finite jog');
        await until(async()=> (await state()).cnc.xyz[0]===.5,'endpoint update');
        await post('heartbeat',body);await sleep(150);child.send({test:'detent',seq:2,axis:'Z',direction:-1});
        await until(()=>messages.filter(m=>m.test==='cnc-write'&&m.data.includes('$J=')).length===2,'second finite jog');
        const lines=messages.filter(m=>m.test==='cnc-write'&&m.data.includes('$J=')).map(m=>m.data.trim());
        assert.deepEqual(lines,['$J=G21G91 X0.5000 F1000.000','$J=G21G91 Z-0.5000 F1000.000']);
        await post('mode',{mode:'adaptive'});
        await until(async()=> (await state()).velocityReady,'timestamped wheel capability');
        assert.equal((await state()).armed,false);await post('arm',body);await sleep(80);
        child.send({test:'wheel',seq:3,period:0});
        await until(async()=> (await state()).cnc.xyz[0]===1,'slow adaptive detent exact .5mm');
        child.send({test:'wheel',seq:4,period:80});
        await until(async()=> (await state()).cnc.xyz[0]===1.5,'second adaptive detent exact .5mm');
        child.send({test:'wheel',seq:5,period:80});
        await until(()=>messages.some(m=>m.test==='cnc-write'&&/\$J=.*F1120\.000/.test(m.data)),'Precision-to-Rapid fast stream');
        for(let seq=6;seq<=65;seq++){
            if(seq%10===0)await post('heartbeat',body);
            child.send({test:'wheel',seq,period:seq%2?10:0});await sleep(20);
        }
        assert.equal((await state()).armed,true,'Fast spinning stays armed');
        assert.equal((await state()).adaptivePhase,'fast');
        assert.ok(messages.some(m=>m.test==='cnc-write'&&/\$J=.*F2000\.000/.test(m.data)),'Ramps to Rapid capped by axis maximum');
        assert.ok(messages.filter(m=>m.test==='cnc-write'&&m.data.includes('$J=')).every(m=>Number(/F([\d.]+)/.exec(m.data)[1])<=2000));
        await sleep(500);
        assert.ok(messages.some(m=>m.test==='cnc-write'&&m.hex==='85'),'release sends exactly one realtime cancel byte');
        assert.equal((await state()).adaptivePhase,'step');
        const quiet=messages.filter(m=>m.test==='cnc-write'&&m.data.includes('$J=')).length;
        await sleep(200);assert.equal(messages.filter(m=>m.test==='cnc-write'&&m.data.includes('$J=')).length,quiet,'no late replay');
        await post('mode',{mode:'step'});await sleep(150);await post('arm',body);await sleep(100);
        await post('heartbeat',body);
        child.send({test:'burst',first:66,count:100});await sleep(150);
        assert.equal((await state()).connected,true);assert.equal((await state()).armed,true);
        assert.ok((await state()).droppedTurns>0);
        child.send({test:'step',stepUm:10000,selection:3});await sleep(250);
        const before=messages.filter(m=>m.test==='cnc-write'&&m.data.includes('$J=')).length;
        assert.equal((await state()).stepMm,10);
        await post('heartbeat',body);await sleep(100);
        assert.equal(messages.filter(m=>m.test==='cnc-write'&&m.data.includes('$J=')).length,before);
        child.send({test:'step',stepUm:10000,selection:0});await sleep(250);
        child.send({test:'detent',seq:166});
        await until(()=>messages.some(m=>m.test==='cnc-write'&&m.data.includes('X10.0000')),'10mm step through packaged backend');
        child.send({test:'detach-esp'});await until(async()=>!(await state()).connected,'disconnect');
        const s=await state();assert.equal(s.armed,false);await sleep(600);
        assert.equal(messages.filter(m=>m.test==='opened'&&m.path==='android-usb:42:0').length,1);
        assert.equal(messages.filter(m=>m.test==='opened'&&m.path==='android-usb:55:0').length,1);
        child.send({test:'allow-stream'});await until(()=>messages.some(m=>m.test==='stream-enabled'),'stream emulator enabled');
        const jogs=()=>messages.filter(m=>m.test==='cnc-write'&&m.data.includes('$J='));
        const cancels=()=>messages.filter(m=>m.test==='cnc-write'&&m.hex==='85').length;
        let baseline=jogs().length,cancelBefore=cancels();
        socket.emit('command','android-usb:42:0','jog:start',{X:1,Y:1},1000,'mm');
        await until(()=>jogs().length>=baseline+4,'dev diagonal jog stream');
        assert.ok(jogs().slice(baseline).every(m=>/X[0-9.]+Y[0-9.]+F/.test(m.data)));
        socket.emit('command','android-usb:42:0','jog:stop');
        await until(()=>cancels()>cancelBefore,'release writes raw 0x85');
        await sleep(180);baseline=jogs().length;await sleep(200);assert.equal(jogs().length,baseline,'no stream after release');
        socket.emit('command','android-usb:42:0','jog:start',{X:1},1000,'mm');
        await until(()=>jogs().length>=baseline+3,'second dev stream');cancelBefore=cancels();
        socket.close();await until(()=>cancels()>cancelBefore,'socket loss cancels owner stream');
        await sleep(180);baseline=jogs().length;await sleep(200);assert.equal(jogs().length,baseline,'socket loss never replays jog');
        assert.deepEqual(messages.filter(m=>m.host==='error'),[],logs);
    }catch(error){error.message+='\nBackend: '+logs.slice(-6500)+'\nMessages: '+JSON.stringify(messages.slice(-25));throw error;}
    finally{socket?.close();await new Promise(resolve=>{child.once('exit',resolve);child.kill();});fs.rmSync(dir,{recursive:true,force:true});}
});
